### ISSUE TITLE
Code for the Interactive bars example

### ISSUE THREAD

**Issue by ghost** [thetylerwolf/tylernwolf.com#1]
Hi,

I have been looking for the code your [ interactive bars example](http://tylernwolf.com/legacy/#/portfolio/corrdisp), but couldn't find it.

Can you please point me to the right file where it's implemented ?

Thank you.

**Comment by thetylerwolf** [comment]
Hi, the whole thing is very much made-to-order and I think built with d3 v3, but you can find the source here: 
https://github.com/thetylerwolf/tylernwolf.com/blob/master/js/finviz_controllers.js

**Comment by ghost** [comment]
thanks!
